### ISSUE TITLE
 Feature request: Enable support for promises in typeORM when using Lazy loading

### ISSUE THREAD

**Issue by abd-almofleh** [daniel7grant/eslint-plugin-typeorm-typescript#10]
Currently, the package is supporting types without Promises 
``` typescript
@Entity('my_data')
export class MyData {
  @Field(() => MyTypeObject)
  @ManyToOne(() => MyTypeObject)
  @JoinColumn()
  group: MyTypeObject;
}
``` 
And since this a relationship and according to TypeORM docs [Lazy Loading](https://orkhan.gitbook.io/typeorm/docs/eager-and-lazy-relations#lazy-relations) to be able to load the relationship object you should mark the type as a promise. Like this: 
```typescript
@Entity('my_data')
export class MyData {
  @Field(() => MyTypeObject,{nullable: false})
  @ManyToOne(() => MyTypeObject,{nullable: false})
  @JoinColumn()
  group: Promise<MyTypeObject>;
}
```
And this is totally a valid and acceptable form and type, yet it shows this error:
```
Type of group in PowerTableRow is not consistent with the TypeORM relation type ManyToOne (expected type: PowerTableGroup).eslint [typeorm-typescript/enforce-relation-types]
```

## Suggestion
The package should get the type inside the promise and check if it's the same as the type in the `Field` decorator

**Comment by daniel7grant** [comment]
Thanks for bringing this to my attention, I was unaware that you could do lazy loading with Promise types. I added checking for Promises in #11. I am collecting the current issues into a bigger release, it will be out in a few days, I hope.

**Comment by abd-almofleh** [comment]
Perfect, thanks, I will test it once it's released.
Thanks again for the quick update

**Comment by daniel7grant** [comment]
I released [v0.3.0](https://github.com/daniel7grant/eslint-plugin-typeorm-typescript/releases/tag/v0.3.0), and added the Promise changes as a feature. Feel free to close if it works for you.

**Comment by abd-almofleh** [comment]
@daniel7grant Unfortunately it's still not working. It gives this error:
```
Type of group in PowerTableRow is not consistent with the TypeORM relation type ManyToOne (expected type: PowerTableGroup).
```
for the code 
```ts
  @Field(() => PowerTableGroup, { nullable: false })
  @ManyToOne(() => PowerTableGroup, {  nullable: false })
  @JoinColumn()
  group!: Promise<PowerTableGroup>;
```

**Comment by daniel7grant** [comment]
Are you sure that you are on the `0.3.0` version, and you restarted your editor (or ran `eslint` from the terminal)? For me both locally, and from a [brand new CodeSandbox](https://codesandbox.io/p/devbox/typeorm-promise-lint-r552lx?file=%2Fsrc%2Fentity%2FUser.ts%3A30%2C1&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clxhy19di00072069zlk5vxsh%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clxhy19dh00022069bik4krje%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clxhy19dh0004206901rv11yn%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clxhy19di00062069d5r19qix%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clxhy19dh00022069bik4krje%2522%253A%257B%2522id%2522%253A%2522clxhy19dh00022069bik4krje%2522%252C%2522activeTabId%2522%253A%2522clxhy92e3009a2069ygfvszjt%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clxhy19dh0001206980wk0izj%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Fentity%252FUser.ts%2522%252C%2522id%2522%253A%2522clxhy92e3009a2069ygfvszjt%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%257D%252C%2522clxhy19di00062069d5r19qix%2522%253A%257B%2522id%2522%253A%2522clxhy19di00062069d5r19qix%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clxhy19dh00052069qgshm6wf%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522start%2522%252C%2522port%2522%253A3000%252C%2522path%2522%253A%2522%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clxhy19dh00052069qgshm6wf%2522%257D%252C%2522clxhy19dh0004206901rv11yn%2522%253A%257B%2522id%2522%253A%2522clxhy19dh0004206901rv11yn%2522%252C%2522activeTabId%2522%253A%2522clxhy1dr2002u2069c8msnndy%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clxhy19dh00032069bj63lkq3%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522start%2522%257D%252C%257B%2522id%2522%253A%2522clxhy1dr2002u2069c8msnndy%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clxhy1dsr001cdbf3a40z9ub7%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D), it works. It passes without issue, and if I change it to be incorrect, it suggest the type with Promise (note the expected type):

![image](https://github.com/daniel7grant/eslint-plugin-typeorm-typescript/assets/15001792/bf193f4d-e5c5-48ea-b2cc-864d290af98d)

**Comment by abd-almofleh** [comment]
My mistake. NPM was stuck and not updating `node_modules` I had to delete the `node_modules` folder and run `npm install` to download the update. 
It is working now, thanks.
