### ISSUE TITLE
Allow the use of array in case of `Jsonb` even if the `array: true` not specificed.

### ISSUE THREAD

**Issue by abd-almofleh** [daniel7grant/eslint-plugin-typeorm-typescript#14]
In TypeORM we have the type `jsonb` which consist of `objects` or `arrays` since it's a normal `JSON` object. The problem in this case:

![image](https://github.com/user-attachments/assets/520d4178-dd25-48a0-a16b-6f727bea014b)

This case is a valid case, but the plugin report an error because the type is `array` but the column type is `jsonb` without `array: true`. Like this:

![image](https://github.com/user-attachments/assets/dc3f4db5-3858-4189-8f81-8332d1ad7c32)

---
So my suggestion is to allow the use of `jsonb` with arrays without specifying `array: true`.

**Comment by daniel7grant** [comment]
Thank you for your issue. I fixed it on master, can you test if it works fine for your use-case? If all is good I'll create a new patch release for you.

**Comment by abd-almofleh** [comment]
Thanks for the quick update, but it did not fix it. Now the error message is clearer, the problem is that the type `MyType` is not matching the `jsonb`. So as I understand if the column type is `jsonb` it needs to accept a valid JSON object

**Comment by daniel7grant** [comment]
I added two tests and it seems to be correct for me now. I realised that it is not easy to test it from master, so I released a version 0.3.1. Can you update and test if it works with this now?

**Comment by abd-almofleh** [comment]
It seems to be working. Thanks
